# This workflow runs the latest CodeQL CLI and checks against CodeQL's Cpp library.
# This is the source for the GitHub Security Code Scanning job.

name: "CodeQL Analysis PR"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'
    
  # Allow manual scheduling
  workflow_dispatch:

jobs:
  analyze:
    name: Analysis
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: c-cpp
          build-mode: manual

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Nuget Packages
        run: nuget restore .\packages.config -PackagesDirectory .\packages\
      - name: Get changed files
        id: get-changed-files
        uses: tj-actions/changed-files@v41
        with:
          separator: ","

     
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          config-file: microsoft/Windows-Driver-Developer-Supplemental-Tools/config/codeql-config.yml@development
          packs: +microsoft/windows-drivers@1.2.0-beta

      - if: matrix.build-mode == 'manual'
        run: |
          $changedFiles = "${{ steps.get-changed-files.outputs.all_changed_files }}".Split(',')
          .\.github\scripts\Build-ChangedSamples.ps1 -ChangedFiles $changedFiles -Verbose

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
